### ISSUE TITLE
Disable bed spawn doesn't work

### ISSUE THREAD

**Issue by BrokenDawn627** [iamshift/NoSleepMod#2]
Version is 1.18.1

**Comment by BrokenDawn627** [comment]
The enchor doesn't work too.

**Comment by shiftthedev** [comment]
if possible provide a log and your mod list so I can check for errors and mod incompatibilities.

**Comment by BrokenDawn627** [comment]
there are too many mods. in my modpack Infinity. https://www.curseforge.com/minecraft/modpacks/infinity-fabric

**Comment by shiftthedev** [comment]
Should be fixed in [1.6.1](https://www.curseforge.com/minecraft/mc-mods/no-sleep/files/3629338)
