### ISSUE TITLE
Version 1.16.5 | rebirth anchor of MOD does not work

### ISSUE THREAD

**Issue by XiFengXF** [iamshift/NoSleepMod#3]
I can't use the mod's respawn anchor in version 1.16.5, Now my modpack really needs to solve this problem. can you fix this? Thanks!
![QQ截图20230105200445](https://user-images.githubusercontent.com/97110012/210776476-fe447ca0-d652-4ed3-8588-884138f273ae.png)

**Comment by shiftthedev** [comment]
I can try but I'll need more info. 
If possible share the lastest.log file after you tried to use the anchor.

**Comment by XiFengXF** [comment]
[latest.log](https://github.com/iamshift/NoSleepMod/files/10352089/latest.log)
Thank you for your help.

**Comment by shiftthedev** [comment]
[1.5.2](https://www.curseforge.com/minecraft/mc-mods/no-sleep-forge/files/4302664) should fix your problem.

**Comment by XiFengXF** [comment]
OK，Thank you for your timely repair.
